version: '3'
services:
  wordpress:
    #image: soulteary/sqlite-wordpress:6.5.3
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
