version: "3.8"
services:
  backend:
    build: ./backend
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      #- ./api/node_modules:/app/node_modules
  frontend:
    build: ./frontend
    container_name: myblog_c
    ports:
      - '3000:3000'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true