services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: fastapi dev src/main.py --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src