# fly.toml app configuration file generated for 01a-python-fast-api-service on 2025-02-05T08:45:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '01a-python-fast-api-service'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
